theme: jekyll-theme-minimal
baseurl: "/workshops"
permalink: /:year/:category/:title.html

exclude: ["notes"]
highlighter: rouge

title : Workshops
description: Berkeley Advanced Media Institute
logo: assets/logo-blue-retina.png
