theme: jekyll-theme-minimal
baseurl: "/workshops"
permalink: /:year/:category/:title.html

# exclude: ["notes"]
highlighter: rouge

title : Data, Charts and Maps
description: Amanda Hickman, Berkeley Advanced Media Institute
logo: assets/advanced_media_inst.png
