theme: jekyll-theme-minimal
baseurl: "/workshops"
permalink: /:year/:category/:title.html

# exclude: ["notes"]
highlighter: rouge

title : Workshops
description: Amanda Hickman
logo_ami: assets/advanced_media_inst.png
logo_j200: assets/ucb_journ.png
